### ISSUE TITLE
Setting paragraph style autoLeading values to whole numbers produces 0% auto leading

### ISSUE THREAD

**Issue by RisingFog** [Agamnentzar/ag-psd#81] opened 2021-09-11 05:30 UTC
I'm working on a project using this library, and came across an issue with the autoLeading value being set to whole numbers (1.0, 1, 2, 2.0, etc.) generating paragraph text with 0% auto leading.

A workaround is setting a value that is very close to the whole number, but never actually equaling the whole number (0.9999, 1.9999, etc.). This will show the percentage value of the whole number in the paragraph's auto leading settings.

**Comment by Agamnentzar** [comment] 2021-09-11 14:02
Can you provide example code that generates wrong file, I can't reproduce it myself

**Comment by RisingFog** [comment] 2021-09-13 07:21
`text: {
      text: "Hello World",
	  style: {
	    autoLeading: true,
    },
      paragraphStyle: {
	autoLeading: 1.0,
      },`

The relevant portion of what triggers the issue for me

**Comment by Agamnentzar** [comment] 2021-09-13 15:36
Can you show me a screenshot which button/menu do you open for this, there's bunch of places where it opens and some of them are global settings and some are per document and I'm really confused which are which now.

**Comment by RisingFog** [comment] 2021-09-13 21:23
It can be found here: 
![image](https://user-images.githubusercontent.com/2121359/133158243-dc7f4fee-3871-43cd-858d-86402c0d9f63.png)

**Comment by Agamnentzar** [comment] 2021-09-13 21:43
Fixed in version `14.3.1` it was incorrect writing for whole number values

**Comment by RisingFog** [comment] 2021-09-13 21:50
Can confirm that 14.3.1 fixes the issue.

Thanks!

**Closed** 2021-09-13 21:50 UTC
